export const PERF_CAPTURE_GENERAL_STATS = 'PERF_CAPTURE_GENERAL_STATS';

export const PERF_CAPTURE_FRAME_RATE_STATS = 'PERF_CAPTURE_FRAME_RATE_STATS';
export const PERF_CAPTURE_RFA_FRAME_RATE_STATS = 'PERF_CAPTURE_RFA_FRAME_RATE_STATS';

export const PERF_CAPTURE_PAINTS_STATS = 'PERF_CAPTURE_PAINTS_STATS';
export const PERF_CAPTURE_USER_STATS = 'PERF_CAPTURE_USER_STATS';